_BASE_: "../cityscapes/semantic-segmentation/swin/maskformer2_swin_large_IN21k_384_bs16_90k.yaml"


DATASETS:
  TRAIN: ("Drivability_train",)
  TEST:  ("Drivability_val",)

INPUT:
  DATASET_MAPPER_NAME: "drivability_semantic_segmentation"
  IMAGE_SIZE: 640
  MIN_SIZE_TRAIN: (640,)
  MAX_SIZE_TRAIN: 640
  MIN_SIZE_TEST: 640
  MAX_SIZE_TEST: 640
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (640, 640)

MODEL:
  WEIGHTS: "/home/felix/workspace/Mask2Former/model_final_2d58d4.pkl"
  SEM_SEG_HEAD:
    NUM_CLASSES: 7
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [2, 2, 6, 2]
    NUM_HEADS: [3, 6, 12, 24]
    WINDOW_SIZE: 7
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD:  [58.395, 57.120, 57.375]

SOLVER:
  IMS_PER_BATCH: 4
  AMP: { ENABLED: True }
  CHECKPOINT_PERIOD: 100     # save ~every 1000 iters
  MAX_ITER: 5000
  MAX_TO_KEEP: 5
TEST:
  EVAL_PERIOD: 1000           # eval & save at the same cadence

MASK_LOGGER:
  ENABLED: True
  PERIOD: 200
  SIZE: (640, 640)

EARLY_STOPPING:
  ENABLED: True
  PATIENCE: 3  # Increase for more patience
  MIN_DELTA: 0.001  # Adjust the minimum improvement threshold
  METRIC_NAME: "sem_seg/mIoU"  # Change to monitor a different metric

OUTPUT_DIR: "output/maskformer2_swin_large_IN21k_384_bs16_90k"
